#!/usr/bin/env python3
"""Emit Dart ML policy (thresholds + trust weights) from evaluation_artifacts/per_class.json."""

from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PER_CLASS = PROJECT_ROOT / "evaluation_artifacts" / "per_class.json"
OUT = (
    PROJECT_ROOT.parent.parent
    / "Flutter"
    / "viva-app"
    / "lib"
    / "features"
    / "ai"
    / "engine"
    / "ml_insight_policy.dart"
)


def threshold_for(recall: float, f1: float, auc: float) -> float:
    if recall <= 0.0:
        return 0.99
    if recall < 0.05:
        return 0.85
    if f1 >= 0.5:
        return max(0.35, min(0.65, 0.70 - f1 * 0.25))
    if auc >= 0.9:
        return 0.40
    return max(0.45, min(0.80, 0.75 - auc * 0.35))


def trust_for(recall: float, auc: float) -> float:
    if recall <= 0.0:
        return 0.15
    return max(0.25, min(1.0, auc * 0.85 + recall * 0.15))


def main() -> None:
    data: dict[str, dict] = json.loads(PER_CLASS.read_text())
    thresholds: dict[str, float] = {}
    trust: dict[str, float] = {}
    rule_confirm: list[str] = []

    for code, m in sorted(data.items()):
        recall = float(m["recall"])
        f1 = float(m["f1"])
        auc = float(m["roc_auc"])
        thresholds[code] = round(threshold_for(recall, f1, auc), 2)
        trust[code] = round(trust_for(recall, auc), 2)
        if recall <= 0.0:
            rule_confirm.append(code)

    def fmt_map(d: dict[str, float], indent: str) -> str:
        lines = [f"{indent}'{k}': {v}," for k, v in d.items()]
        return "\n".join(lines)

    rule_confirm_dart = ",\n  ".join(f"'{c}'" for c in rule_confirm)

    dart = f"""// Generated by viva-Ai/scripts/export_ml_policy.py — do not edit by hand.
// Source: evaluation_artifacts/per_class.json (test-set precision/recall/AUC).

/// Per-class ML score cutoffs tuned from the v1 evaluation sweep.
/// Classes with 0 test recall use 0.99 so they never surface from ML alone.
const Map<String, double> kMlInsightThresholds = <String, double>{{
{fmt_map(thresholds, "  ")}
}};

/// Trust weight for ranking blended insights (0..1, from ROC-AUC + recall).
const Map<String, double> kMlClassTrust = <String, double>{{
{fmt_map(trust, "  ")}
}};

/// ML may suggest these codes only when the rule engine agrees (recall == 0).
const Set<String> kMlRuleConfirmRequired = <String>{{
  {rule_confirm_dart}
}};

/// Budget-risk head: surface coach pressure above this score.
const double kMlBudgetRiskCoachThreshold = 0.65;

/// Mood head: surface coach warning below this score (0 = low mood).
const double kMlMoodDipCoachThreshold = 0.35;

class MlInsightPolicy {{
  const MlInsightPolicy._();

  static double thresholdFor(String code, {{double fallback = 0.30}}) {{
    return kMlInsightThresholds[code] ?? fallback;
  }}

  static double rankScore(String code, double rawScore, {{required bool fromMl}}) {{
    if (!fromMl) return rawScore;
    final trust = kMlClassTrust[code] ?? 0.5;
    return rawScore * trust;
  }}

  static bool dropMlOnly(String code) => kMlRuleConfirmRequired.contains(code);

  static bool shouldInjectBudgetCoach(double? budgetRisk) =>
      budgetRisk != null && budgetRisk >= kMlBudgetRiskCoachThreshold;

  static bool shouldInjectMoodCoach(double? predictedMood) =>
      predictedMood != null && predictedMood <= kMlMoodDipCoachThreshold;
}}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(dart, encoding="utf-8")
    print(f"Wrote {OUT} ({len(thresholds)} classes, {len(rule_confirm)} rule-confirm)")


if __name__ == "__main__":
    main()
